# 1. Statisches Framework Flag für Firebase
$RNFirebaseAsStaticFramework = true
use_modular_headers!

require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'

prepare_react_native_project!

ENV['RCT_NEW_ARCH_ENABLED'] = '1'

target 'SkillForge' do
  config = use_native_modules!

  # WICHTIG: Erzeugt die benötigten Swift-Header (*-Swift.h) für FirebaseAuth
  use_frameworks! :linkage => :static

  use_react_native!(
    :path => config[:reactNativePath],
    :new_arch_enabled => true,
    :fabric_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        build_config.build_settings['DEFINES_MODULE'] = 'YES'

        # Zwingt Xcode dazu, Swift-Header-Dateien zu generieren
        build_config.build_settings['SWIFT_INSTALL_OBJC_HEADER'] = 'YES'
      end
    end
  end
end